### ISSUE TITLE
Support for celery 5.x.x

### ISSUE THREAD

**Issue by aakash2610** [ZeitOnline/celery_longterm_scheduler#6]
I tried to use this repo with Celery v5.0.2. This code does not work. 
It is giving me error:
`AttributeError: module 'celery.bin.base' has no attribute 'Command'`

I looked at the celery and found out that Command class has been removed since v5.0.0. Can you please fix the code to support the latest celery version?

Thanks,

**Comment by jeffreybrowning** [comment]
Any movement on this?

**Comment by wosc** [comment]
Hi there. We do have "update celery from 4.x to 5.x throughout our projects" in our backlog, but there's no date yet when we will be able to get to it.

From reading the celery docs ([one](https://docs.celeryproject.org/en/latest/history/whatsnew-5.0.html#new-command-line-interface), [two](https://docs.celeryproject.org/en/latest/userguide/extending.html#extending-command-options)), the main bw-incompatible change in 5.x seems to be that they've replaced their custom CLI mechanics with [click](https://click.palletsprojects.com/). Thus, our [Command](https://github.com/ZeitOnline/celery_longterm_scheduler/blob/master/src/celery_longterm_scheduler/scheduler.py#L84) setup here needs to be adjusted to that new API. I'm hoping that should be rather straightforward, but as I said, not sure when we'll have the capacity. So if one of you wants to tackle this, I'd be more than happy to merge a patch.

**Comment by jeffreybrowning** [comment]
@wosc Thanks for the direction!
